[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.x"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.3.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "~1.3.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "~1.3.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true