name: Test go build

on:
  pull_request:
    # paths:
    #   - "functions/**"
    #   - "package.json"
    #   - "go.mod"

jobs:
  dry_deploy:
    name: dry serverless deployment
    runs-on: ubuntu-latest
    env:
      nodejs-version: 18.x

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.2

      - name: Install go dependencies
        run: |
          go version
          go mod download

      - name: Run build
        run: make build

      - name: Validate
        working-directory: functions/redirect
        run: |
          go vet .
          go test -v

      - name: Use Node.js ${{ env.nodejs-version }}
        uses: actions/setup-node@v4
        with:
          nodejs-version: ${{ env.nodejs-version }}

      - run: yarn install --frozen-lockfile

      - name: Install Plugins and Validate
        uses: serverless/github-action@v3.2
        with:
          args: -c "serverless package"
          entrypoint: /bin/sh
